name: Frontend CI/CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Build and test
        run: npm run build && npm test

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Build and push Docker image
        run: |
          gcloud auth configure-docker gcr.io
          docker build -t gcr.io/receipt/receipt-frontend:${{ github.sha }} .
          docker push gcr.io/receipt/receipt-frontend:${{ github.sha }}
      - name: Deploy to Cloud Run (Stable)
        run: |
          gcloud run deploy frontend-stable \
            --image gcr.io/receipt/frontend:${{ github.sha }} \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars BACKEND_URL=${{ secrets.BACKEND_URL }}
      - name: Deploy to Cloud Run (Canary)
        run: |
          gcloud run deploy frontend-canary \
            --image gcr.io/<project-id>/frontend:${{ github.sha }} \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars BACKEND_URL=${{ secrets.BACKEND_URL }}
      - name: Traffic Splitting
        run: |
          gcloud run services update-traffic frontend-stable \
            --to-revisions frontend-stable=90,frontend-canary=10 \
            --region us-central1
